### ISSUE TITLE
Is separate bridge for each VLAN really necessary?

### ISSUE THREAD

**Issue by rosowiecki** [schreiberstein/trunk-tap.py#1]
Hello!

https://unix.stackexchange.com/questions/192177/does-linux-virtual-bridge-support-vlans

In the link above they claim that it's enough to create vlan subdevices on bridge interface which connects raw devices (like: eth0 and tap0), hovewer I haven't tested it yet, I just want to understand it first. Why your solution explicitely creates separate bridge on each vlan?

**Comment by schreiberstein** [comment]
Hello!

I believe I have tried this, but it did not work.
There is an alternative linux bridge driver out there from a project called Cumulus Linux which supports something called "VLAN aware bridged" which is exactly what you are talking about.

I might be wrong on this. I will experiment with that kind of stuff further.
For my personal setup at home, I am connecting my networks via wireguard and a vxlan bridge.
I am looking into some of the Cumulus stuff because it would be pretty neat to bridge every single VLAN without having to clutter your ifconfig-screen with thousands of interfaces.

If you find out a more efficient method, please let me know.
I'd love to hear about it.

Have a great day and sorry for the delayed reply.

Alexander Schreiber

**Comment by rosowiecki** [comment]
Hi again!

In order to bridge two office locations, I did the following (on CentOS 7)
* bridged tapX and ethX devices on both sides
* create vlan subdevices on bridge like br0.15, br0.17 etc. -- i didn't have to create tap0.15 or eth0.15 vlan devices (which was good news), but:
* BAD NEWS: I had to assign IP numbers to br0.XX devices on both sides
I don't know why last step was neccessary: maybe bridge driver in Linux transmits ARP broadcast packets only if they match some network mask on the bridge device? Maybe that was the reason it didn't work for you either?

I suppose bridge driver behaviour is different when it connets tap.XX ant eth.XX vlan devices directly... I didn't have enough time for experiments :) And if you need two free IP's from each vlan it's not possible to automate the whole thing like your script does anyway.

I had only 3 vlans to configure, so I did it manually -- with dozens of vlans your script seems to do better job.

Regards,
Robert Osowiecki

**Comment by schreiberstein** [comment]
Hello there!

Thank you for those interesting findings.
I experimented quite a bit with different methods because I also was not happy with the amount of interfaces in 'ifconfig', and the one currently implemented in this script is the one I found to be the best.

If you find a better way, please let me know.

What I like about this method is that the machine itself does not need to interact with the traffic on these interfaces in any way. No need to configure IP-addresses, etc. It's just a simple, brain-dead bridge which does what it's supposed to do.

Best regards,
Alexander Schreiber
